server{
    listen 80;
    server_name localhost;

    root /app;
    index index.php index.html inde.htm;

    location / {
        try_files $uri /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass drupal_prod:9000;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }   
}
