events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        
        # Ruta donde está instalado Drupal (debe coincidir con el volumen montado)
        root /var/www/html;
        index index.php index.html index.htm;

        # Configuración para URLs limpias de Drupal
        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Configuración para PHP
        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass drupal_prod:9000;  # Nombre del servicio Drupal + puerto
            fastcgi_index index.php;
            include fastcgi_params;
            
            # Ajuste crítico para Drupal
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
        }

        # Bloqueo de acceso a archivos sensibles
        location ~ /\. {
            deny all;
        }
    }
}

