version: '3.8'

services:
  # Bloque PostgreSQL y Nginx
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      production_net:
        ipv4_address: 172.30.0.11
      services_net:
        ipv4_address: 172.20.0.11
    command: ["postgres", "-c", "shared_preload_libraries=pg_trgm"]
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - drupal_data:/var/www/html
    ports:
      - "80:80"
    networks:
      production_net:
        ipv4_address: 172.30.0.12
    depends_on:
      - db
    restart: always

  drupal:
    image: drupal:php8.3-fpm
    container_name: drupal_prod
    depends_on:
      - db
    environment:
      DRUPAL_DB_HOST: ${DRUPAL_DB_HOST}
      DRUPAL_DB_NAME: ${DRUPAL_DB_NAME}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASSWORD: ${DRUPAL_DB_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      production_net:
        ipv4_address: 172.30.0.10
    volumes:
      - drupal_data:/var/www/html
    restart: always

  # Bloque Apache y MySQL
  mysql:
    image: mysql:latest
    container_name: db.dev.local
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      private_network:
        ipv4_address: 172.40.0.10
    volumes:
      - mysql_data:/var/lib/mysql

  webserver:
    image: httpd:latest
    container_name: dev.local
    restart: always
    networks:
      private_network:
        ipv4_address: 172.40.0.11
    volumes:
      - ./html:/usr/local/apache2/htdocs
      - ./apache-conf:/usr/local/apache2/httpd.conf

  # Bloque NAS + DNS Server
  nas_dns:
    image: debian:latest
    container_name: nas_dns
    tty: true
    networks:
      services_net:
        ipv4_address: 172.20.0.10
    volumes:
      - nas_data:/mnt/backups
      - ./backup_scripts:/scripts
      - ./dns_config:/etc/bind
    command: bash
    restart: always

networks:
  # Red de servicios para NAS y DNS
  services_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
        
  # Red de producción para PostgreSQL y Nginx
  production_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

  # Red privada para MySQL y Webserver
  development_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.40.0.0/24


volumes:
  pg_data:
  drupal_data:
  nas_data:
  mysql_data:
