FROM debian:latest

RUN apt-get update && \
    apt-get install -y bind9 bind9utils bind9-doc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY dns_config/ /etc/bind/

EXPOSE 53/udp 53/tcp

CMD ["named", "-g", "-c", "/etc/bind/named.conf"]	
