#----------------------------CONTENEDORES-------------------------------#

services:

  # Bloque NAS + DNS Server
  nas_dns:
    image: debian:latest
    container_name: nas_serv
    restart: always
    privileged: true
    command: bash ./backups/inicio.sh
    environment:
      MYSQL_ROOT_PASSWORD: password
      POSTGRES_PASSWORD: password
    volumes:
      - ./services/nas_data/backups:/backups
    dns:
      - 172.20.0.6
    networks:
      bridge_local: {}
      services_net:
        ipv4_address: 172.20.0.5
    tty: true

  bind9:
    build:
      context: ./services/bind
    container_name: bind9_serv
    restart: always
    dns:
      - 172.20.0.6
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./services/bind/config:/etc/bind
      - ./services/bind/config/zones:/etc/bind/zones
      - dns_cache:/var/cache/bind
      - dns_logs:/var/log
    environment:
      - BIND9_USER=root
    networks:
      bridge_local: {}
      services_net:
        ipv4_address: 172.20.0.6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1

  # Bloque PostgreSQL y Nginx
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    volumes:
      - postgre_data:/bitnami/postgresql
    environment:
      POSTGRESQL_DATABASE: drupal
      POSTGRESQL_USERNAME: drupal
      POSTGRESQL_PASSWORD: password
    dns:
      - 172.20.0.6
    networks:
      production_net:
        ipv4_address: 172.30.0.7

  nginx:
    image: bitnami/nginx:latest
    container_name: nginx_prod
    restart: always
    volumes:
      - ./production/server-block.conf:/opt/bitnami/nginx/conf/server_blocks/server-block.conf
      - prod_data:/app
    ports:
      - "8080:80"
    dns:
      - 172.20.0.6
    networks:
      bridge_local: {}
      production_net:
        ipv4_address: 172.30.0.5
    depends_on:
      - postgresql

  phpfm:
    image: 'bitnami/php-fpm:8.1'
    container_name: phpfm
    restart: always
    entrypoint: bash /iniciodrupal.sh
    volumes:
      - ./production/iniciodrupal.sh:/iniciodrupal.sh
      - ./production/php.ini:/opt/bitnami/php/etc/php.ini
      - prod_data:/app
    environment:
      - PHP_ENABLE_OPCACHE=1
    dns:
      - 172.20.0.6
    networks:
      bridge_local: {}
      production_net:
        ipv4_address: 172.30.0.6
    depends_on:
      - postgresql



  # Bloque Apache y MySQL
  mysql:
    image: mysql:latest
    container_name: db.dev.local
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    dns:
      - 172.20.0.6
    networks:
      development_net:
        ipv4_address: 172.40.0.6


  dev.local:
    image: drupal:10-apache
    container_name: dev.local
    restart: always
    volumes:
      - dev_data:/var/www/html/ 
    ports:
      - "8081:80"
    dns:
      - 172.20.0.6
    networks:
      bridge_local: {}
      development_net:
        ipv4_address: 172.40.0.5
    depends_on:
      - mysql

  # Bloque Servidores SSH
  ssh_services:
    build: ./services/ssh_services
    container_name: ssh_services
    restart: always
    networks:
      bridge_local: {}
      services_net:
        ipv4_address: 172.20.0.9
    ports:
      - "2222:22"
    volumes:
      - ./services/ssh_services/authorized_keys:/home/john/.ssh/authorized_keys:ro

  ssh_development:
    build: ./development/ssh_development
    container_name: ssh_development
    restart: always
    networks:
      bridge_local: {}
      development_net:
        ipv4_address: 172.40.0.9
    ports:
      - "2223:22"
    volumes:
      - sshdev_data:/home/john


#------------------------NETWORKS--------------------#
networks:
  bridge_local:
    driver: bridge

  services_net:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

  production_net:
    driver: macvlan
    driver_opts:
      parent: ens19
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.1

  development_net:
    driver: macvlan
    driver_opts:
      parent: ens20
    ipam:
      config:
        - subnet: 172.40.0.0/24
          gateway: 172.40.0.1


#--------------------------VOLUMENES-----------------------#
volumes:
  dev_data:
  mysql_data:
  prod_data:
  postgre_data:
  dns_cache:
  dns_logs:
  sshdev_data:  
