services:
   postfix_mail:
     build:
       context: ./postfix_mail
     container_name: postfix_mail
     restart: always
     cap_add:
       - NET_ADMIN
     dns:
       - 172.20.0.0.6
     networks:
       production_prueba:
         ipv4_address: 172.30.0.15
     ports:
       - "2525:25"
     volumes:
       - maildata:/var/mail
       
networks:
  production_prueba:
    driver: bridge

volumes:
  maildata:
