listen=YES
listen_ipv6=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_root=/data/publico
anon_umask=022
dirmesage_enable=NO
use_localtime=YES
xferlog_enable=NO
connect_from_port_20=YES
chroot_local_user=NO
allow_writeable_chroot=NO
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010