# Configuración global
user nginx;          # Usuario que ejecuta Nginx
worker_processes 1;  # Número de procesos de trabajo
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;  # Máximo de conexiones por trabajador
}

http {
    include       /etc/nginx/mime.types;  # Tipos de archivo MIME
    default_type  application/octet-stream;
    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    
    sendfile on;  # Habilitar la transferencia de archivos más eficiente
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;  # Tiempo de espera para conexiones inactivas
    types_hash_max_size 2048;

    include /etc/nginx/conf.d/*.conf;  # Incluir configuraciones adicionales

    server {
        listen 80;  # Puerto en el que escucha Nginx
        server_name localhost;  # Nombre de dominio o dirección IP

        # Directorio de archivos estáticos
        location / {
            root /usr/share/nginx/html;  # Directorio donde están los archivos
            index index.html index.htm;  # Archivos de índice
        }

        # Manejo de errores
        error_page  404              /404.html;
        error_page   500 502 503 504  /50x.html;
        
        # Ubicación de los archivos de error personalizados
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }
}
